### ISSUE TITLE
Error a compilar EnviarCorreo.Nativo

### ISSUE THREAD

**Issue by rauldvlpr** [aminespinoza/EnviaCorreosXamarinApp#1]
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "ResolveLibraryProjectImports" task failed unexpectedly.
System.IO.FileNotFoundException: Could not load assembly 'EnviarCorreo.Forms, Version=, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'EnviarCorreo.Forms.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(String fullName, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(String fullName)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.GetAssembly(String fileName)
   at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract(ICollection`1 jars, ICollection`1 resolvedResourceDirectories, ICollection`1 resolvedAssetDirectories, ICollection`1 resolvedEnvironments)
   at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	EnviarCorreo.Nativo

**Comment by aminespinoza** [comment]
Esto veo que sucede cuando ejecutas tu aplicación de Forms. En modo nativo te funcionó?

**Comment by rauldvlpr** [comment]
Sale el mismo error y 
`Severity	Code	Description	Project	File	Line	Suppression State
Error		The "XamlCTask" task could not be instantiated from "C:\Users\rauld\OneDrive\Raul\AppUniversity\Xamarin\Desafio 1\EjercicioBase\packages\Xamarin.Forms.2.0.0.6482\build\portable-win+net45+wp80+win81+wpa81+MonoAndroid10+MonoTouch10+Xamarin.iOS10\Xamarin.Forms.Build.Tasks.dll". Could not load file or assembly 'Xamarin.Forms.Build.Tasks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)	EnviarCorreo.Forms			
`

**Comment by Disada** [comment]
No es posible compilar por ese error, me sale lo mismo
Error		La tarea "XamlCTask" se declaró o usó incorrectamente o generó un error durante la construcción. Compruebe la ortografía de los nombres de la tarea y del ensamblado.	EnviarCorreo.Forms

**Comment by aminespinoza** [comment]
El error es altamente común por la discrepancia de versiones en Xamarin, les pido por favor ayuda para actualizar sus entornos con la última versión del SDK de Android y Xamarin en general, esto lo puede solucionar.

**Comment by jpd21122012** [comment]
Error de compilacion;Severity	Code	Description	Project	File	Line	Suppression State
Error		No resource found that matches the given name: attr 'windowNoTitle'.	EnviarCorreo.Forms.Droid	EnviarCorreo.Forms\EnviarCorreo.Forms.Droid\Resources\values\styles.xml	2

**Comment by oscarsapito** [comment]
Gravedad	Código	Descripción	Proyecto	Archivo	Línea	Estado suprimido
Mensaje	IDE1006	Infracción de la regla de nomenclatura: Estas palabras no pueden comenzar por caracteres en mayúscula: btnReportar_Click	EnviarCorreo.Nativo	D:\EnviaCorreosXamarinApp-master\EjercicioBase\EnviarCorreo.Nativo\MainActivity.cs	25	Activo

**Comment by oscarsapito** [comment]
Actualize el SDK , y sigue error...alguna solucion por favor

**Comment by aminespinoza** [comment]
Hola apenas veo esto de nuevo, sigues teniendo problemas o cerramos el Issue?

**Comment by AxelPantoja** [comment]
Hola, al compilar la aplicación para el evento de cognitive services me da el error, sigue sin funcionar, cómo puedo verificar mi registro?
